version: '3'
services:
  
  encoding_app:
    image: quay.io/n1analytics/encoding-service
    ports:
     - "8000:8080"
    environment:
     - CLKHASH_SERVICE_DB_URI=postgresql://postgres:secret@postgres:5432/postgres
     - CLKHASH_SERVICE_BROKER_URI=sqla+postgresql://postgres:secret@postgres:5432/postgres
    entrypoint:
     - waitress-serve
     - --port=8080
     - clkhash_service:connexion_app
    depends_on:
      - encoding_db_init
      - postgres

  encoding_worker:
    image: quay.io/n1analytics/encoding-service
    environment:
     - CLKHASH_SERVICE_DB_URI=postgresql://postgres:secret@postgres:5432/postgres
     - CLKHASH_SERVICE_BROKER_URI=sqla+postgresql://postgres:secret@postgres:5432/postgres
    entrypoint:
     - celery
     - -A
     - clkhash_worker
     - worker
    depends_on:
      - encoding_db_init
      - postgres
    deploy:
      replicas: 2

  encoding_db_init:
    image: quay.io/n1analytics/encoding-service
    environment:
     - CLKHASH_SERVICE_DB_URI=postgresql://postgres:secret@postgres:5432/postgres
    entrypoint:
     - python3
     - database.py
     - init
    depends_on:
      - postgres

  postgres:
    image: "postgres:11-alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - psql:/var/lib/postgresql/data

volumes:
  psql:
