version: '3.4'
services:
  
  encoding_app:
    image: data61/anonlink-encoding-service:latest
    ports:
     - "8000:8080"
    environment:
     - CLKHASH_SERVICE_DB_URI=postgresql://postgres:secret@postgres:5432/postgres
     - CLKHASH_SERVICE_BROKER_URI=sqla+postgresql://postgres:secret@postgres:5432/postgres
    entrypoint:
     - waitress-serve
     - --port=8080
     - clkhash_service:connexion_app
    depends_on:
      - encoding_db_init
      - postgres

  encoding_worker:
    image: data61/anonlink-encoding-service:latest
    environment:
     - CLKHASH_SERVICE_DB_URI=postgresql://postgres:secret@postgres:5432/postgres
     - CLKHASH_SERVICE_BROKER_URI=sqla+postgresql://postgres:secret@postgres:5432/postgres
    command:
     - celery
     - -A
     - clkhash_worker
     - worker
    depends_on:
      - encoding_db_init
      - postgres

  encoding_db_init:
    image: data61/anonlink-encoding-service:latest
    environment:
     - CLKHASH_SERVICE_DB_URI=postgresql://postgres:secret@postgres:5432/postgres
    entrypoint: /bin/sh -c "dockerize -wait tcp://postgres:5432 python3 database.py init"
    depends_on:
      - postgres

  postgres:
    image: "postgres:11"
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - psql:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q -h db -p 5432 -U postgres
      interval: 5s
      timeout: 30s
      retries: 5

volumes:
  psql:
