swagger: '2.0'

info:
  title: Clkhash REST API
  version: 0.0.3
  description: A simple REST wrapper around clkhash.

  contact:
    name: N1 Analytics
    url: https://github.com/n1analytics/clkhash-service
    email: jakub.nabaglo@data61.csiro.au

schemes:
  - http

tags:
  - name: project
    description: TODO

  - name: clk
    description: TODO

paths:
  /projects/:
    get:
      summary: List existing linkage projects.
      description: Lists the IDs of existing linkage projects. Every linkage project has a unique ID. To retrieve more information about a project, use `/projects/{project_id}`.
      tags:
        - projects
      operationId: clkhash_service.get_projects
      produces:
        - application/json
      responses:
        200:
          description: List of linkage projects.

  /projects/{project_id}:
    parameters:
      - $ref: '#/parameters/project_id'

    post:
      summary: Add a new linkage project.
      description: TODO
      tags:
        - projects
      operationId: clkhash_service.post_project
      consumes:
        - application/json
      parameters:
        - name: schema
          in: body
          required: true
          schema: {}
        - name: key1
          in: query
          type: string
          required: true
        - name: key2
          in: query
          type: string
          required: true
      responses:
        201:
          description: Successfully created project.
        409:
          description: Project with this ID already exists.
        422:
          description: The schema is not valid.

    get:
      summary: Retrieve properties of the specified project.
      description: TODO
      tags:
        - projects
      operationId: clkhash_service.get_project
      responses:
        200:
          description: Properties of specified object.

    delete:
      summary: Delete the linkage project.
      description: TODO
      tags:
        - projects
      operationId: clkhash_service.delete_project
      responses:
        200:
          description: Successfully deleted.
        202:
          description: Marked for deletion.

  /projects/{project_id}/clks/:
    parameters:
      - $ref: '#/parameters/project_id'

    get:
      summary: Get status of all clks.
      description: TODO
      tags:
        - projects
      operationId: clkhash_service.get_clks_status
      responses:
        200:
          description: List of clks along with status.

    post:
      summary: Post PII to hash.
      description: TODO
      tags:
        - projects
      operationId: clkhash_service.post_pii
      consumes:
        - text/csv
      parameters:
        - name: pii_table
          in: body
          required: true
          schema:
            type: string
        - name: header
          description: 'Set to `true` if the csv input has a header row.'
          in: query
          type: boolean
          required: false
          default: false
        - name: validate
          description: 'If `true`, validate the PII before hashing.'
          in: query
          type: boolean
          required: false
          default: true
      responses:
        202:
          description: Successfully sent for hashing.

  /projects/{project_id}/clks/{clk_start_index}/{clk_number}:
    parameters:
      - $ref: '#/parameters/project_id'
      - name: clk_start_index
        in: path
        description: The index of the first clk to operate on.
        required: true
        type: integer
        minimum: 0
      - name: clk_number
        in: path
        description: The number of clks to operate on.
        required: true
        type: integer
        minimum: 1

    get:
      summary: Retrieve the clks, if available.
      description: TODO
      tags:
        - projects
      operationId: clkhash_service.get_clks
      responses:
        102:
          description: The clks are still being processed.
        200:
          description: The clks are available and returned.
        207:
          description: Some of the clks are available. Details listed.
        422:
          description: The PII submitted did not satisfy the schema.

    delete:
      summary: If finished hashing, delete the clks. Otherwise, abandon hashing and delete the PII.
      description: TODO
      tags:
        - projects
      operationId: clkhash_service.delete_clks
      responses:
        202:
          description: Marked for deletion.
        204:
          description: Successfully deleted.

parameters:
  project_id:
    name: project_id
    in: path
    description: The ID of the linkage project. Must be unique.
    required: true
    type: string
