name: encoding-service
description: A service for encoding PII into CLKs.
version: 0.0.3
apiVersion: v1
keywords:
  - clks
sources:
  - https://github.com/data61/anonlink-encoding-service/
  - https://github.com/data61/clkhash/
maintainers:
  - name: Confidential Computing Team at CSIRO's Data61
    url: https://data61.csiro.au
