debug: false

app:
  image:
    repository: "data61/anonlink-encoding-service"
    tag: "latest"

  replicas: 1
  resources:
    #limits:
    #  memory: 512Mi
    #  cpu: 4
    requests:
      cpu: 200m
      memory: 256Mi

  #podAnnotations:

service:
  ## For minikube, set this to NodePort, elsewhere use LoadBalancer
  ## Use ClusterIP if your setup includes an ingress controller.
  type: ClusterIP
  servicePort: 80

  annotations: {}

  labels: {}

  ## Use loadBalancerIP to request a specific static IP,
  ## otherwise leave blank
  ##
  # loadBalancerIP:

  ## Address that are allowed when svc is LoadBalancer
  ##
  loadBalancerSourceRanges: []

workers:
  image:
    repository: "data61/anonlink-encoding-service"
    tag: "latest"

  replicas: 2
  resources:
    #limits:
    #  memory: 512Mi
    #  cpu: 4
    requests:
      cpu: 200m
      memory: 256Mi


provision:
  postgresql: true

jobs:
  initdb:
    enabled: true
    image:
      repository: "data61/anonlink-encoding-service"
      tag: "latest"

global:
  postgresql:
    postgresqlDatabase: "postgres"
    postgresqlUsername: "postgres"
    postgresqlPassword: "secret"

postgresql:
  # See available settings and defaults at:
  # https://github.com/bitnami/charts/tree/master/bitnami/postgresql
  nameOverride: "postgres"

  persistence:
    enabled: false
    storageClass: "default"
    size: 8Gi

  metrics:
    enabled: true
  resources:
    #limits:
    #  memory: 8Gi
    requests:
      #memory: 1Gi
      cpu: 100m
