{{/* Define a few database URI variables */}}
{{- $dbAddress := printf "%s-%s" .Release.Name .Values.postgresql.nameOverride -}}
{{- $dbURI := printf "postgresql://postgres:%s@%s:5432/postgres" .Values.global.postgresql.postgresqlPassword $dbAddress -}}
{{- $brokerURI := printf "sqla+%s" $dbURI -}}
apiVersion: v1
kind: Secret
metadata:
  name: encoding-secrets
  labels:
    {{- include "release_labels" . | indent 4 }}
data:
  postgresPassword: {{ .Values.global.postgresql.postgresqlPassword | b64enc | quote }}
  databaseURI: {{ $dbURI | b64enc | quote }}
  brokerURI: {{ $brokerURI | b64enc | quote }}

