apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "release_labels" . | indent 4 }}
  name: encoding-app
spec:
  type: {{ .Values.service.type }}
  {{- if and .Values.service.loadBalancerIP (eq .Values.service.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: "http"
    port: {{ .Values.service.port }}
    targetPort: encodingservice
  selector:
    component: encoding-app
    release: {{ .Release.Name }}
