apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "release_labels" . | indent 4 }}
  name: encoding-app
spec:
  type: LoadBalancer
  ports:
  - name: "8000"
    port: 80
    targetPort: 8080
  selector:
    component: encoding-app
    release: {{ .Release.Name }}
