{{- $dbAddress := printf "%s-%s" .Release.Name .Values.postgresql.nameOverride -}}
{{- if .Values.jobs.initdb.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: encoding-initdb
  annotations:
    # This job only gets executed on install, not after an upgrade.
    # Manual intervention (or a job with a post-upgrade hook) is required to migrate a
    # production database.
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: encoding-initdb
    spec:
      restartPolicy: "OnFailure"
      initContainers:
        - name: wait-for-db
          image: postgres
          command: ['sh', '-c',
                    'until pg_isready -h {{ $dbAddress }} -p 5432; do echo "waiting for database"; sleep 2; done;']
      containers:
      - name: dbinit
        image: {{ .Values.jobs.initdb.image.repository }}:{{ .Values.jobs.initdb.image.tag }}
        command:
        - python3
        - database.py
        - init
        env:
        - name: CLKHASH_SERVICE_DB_URI
          valueFrom:
            secretKeyRef:
              name: encoding-secrets
              key: databaseURI
{{- end }}
