{{-  $dbAddress := printf "%s-%s" .Release.Name .Values.postgresql.nameOverride -}}
{{-  $dbURI := printf "postgresql://postgres:%s@%s:5432/postgres" .Values.postgresql.postgresPassword $dbAddress -}}
{{-  $brokerURI := printf "sqla+$dbURI" -}}
apiVersion: v1
kind: Secret
metadata:
  name: encoding-secrets
  labels:
    {{- include "release_labels" . | indent 4 }}
data:
  postgresPassword: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
  databaseURI: {{ $dbURI | b64enc | quote }}
  brokerURI: {{ $brokerURI | b64enc | quote }}

